## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/

In [1]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [2]:
!nvidia-smi

Thu Dec 28 02:06:16 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090         On | 00000000:1D:00.0 Off |                  N/A |
| 30%   36C    P8               34W / 350W|  13097MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.2


## introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()`

In [4]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

### Rnadom tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3879, 0.1137, 0.2125, 0.5477],
        [0.1771, 0.3570, 0.1639, 0.0199],
        [0.1233, 0.7611, 0.8863, 0.5972]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.arange()
one_to_ten = torch.arange(start = 0, end = 1000, step =77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tnesors not on the right device

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype = None, # what is datatype is the tensor (e.g. float32 or float16)
                               device = "cuda:2", # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.], device='cuda:2')

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [30]:
float_16_tensor

tensor([3., 6., 9.], device='cuda:2', dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:2')

In [32]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long, device = "cuda:2")
int_32_tensor

tensor([3, 6, 9], device='cuda:2')

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], device='cuda:2')

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tnesors not on the right device - to get device from a tensor, can use `tensor.device`

In [34]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[8.3627e-01, 1.8261e-01, 5.9387e-01, 1.4402e-01],
        [8.3155e-01, 2.8402e-01, 6.7113e-01, 7.2652e-04],
        [8.6883e-02, 1.7086e-01, 5.5558e-02, 5.7340e-01]])

In [35]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [36]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[8.3627e-01, 1.8261e-01, 5.9387e-01, 1.4402e-01],
        [8.3155e-01, 2.8402e-01, 6.7113e-01, 7.2652e-04],
        [8.6883e-02, 1.7086e-01, 5.5558e-02, 5.7340e-01]])
Datatype of tensor: torch.float32
Shape of tensor: <built-in method size of Tensor object at 0x7f8821e37880>
Device tensor is on: cpu


### Manipulate Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Muliplication (element-wise)
* Division
* Matrix multiplication

In [37]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply tensor by 10
tensor = tensor* 10

In [39]:
tensor

tensor([10, 20, 30])

In [40]:
# Substract 10
tensor -10

tensor([ 0, 10, 20])

In [41]:
# Try out pytorch in-built functions
torch.mul(tensor,10)

tensor([100, 200, 300])

In [42]:
torch.add(tensor,10)

tensor([20, 30, 40])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [43]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [44]:
# Matrix mulitplication
torch.matmul(tensor, tensor)

tensor(1400)

In [45]:
tensor @ tensor

tensor(1400)

In [46]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 0 ns, sys: 2.55 ms, total: 2.55 ms
Wall time: 1.69 ms


tensor(1400)

In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 60 µs, sys: 14 µs, total: 74 µs
Wall time: 79.9 µs


tensor(1400)

In [49]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

In [ ]:
torch.matmul(torch.rand(10,2), torch.rand(2,10)).shape

### One of the most common errors in deep laerning: shape errors

In [51]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [52]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [54]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [55]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [56]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [59]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above, tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Finding the min, max, mean, sum, etc (tensor aggregation)

In [67]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [62]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [63]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [74]:
# Find the mean - note : the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [75]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [85]:
x+=1

In [86]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [87]:
x.argmin()

tensor(0)

In [88]:
x[0]

tensor(1)

In [89]:
x.argmax()

tensor(9)

In [90]:
x[9]

tensor(91)

## Reshpaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `l` dimensions from a tensor
* Unsqeeze -add a `l` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [104]:
import torch

x = torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [105]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [106]:
# Change th e view

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [107]:
#  Changing z changes x (becuase a view of a tensor shares the same memory as teh original
z[:,0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [110]:
# Stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [114]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [117]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [118]:
# torch.permute = rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224,224,3))

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [119]:
x_original[0,0,0]

tensor(0.9260)

In [112]:
x_reshaped.shape

torch.Size([1, 9])

In [113]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing numpy

In [122]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [123]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [125]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [126]:
x[0][0][0]

tensor(1)

In [127]:
x[:, 0]

tensor([[1, 2, 3]])

In [128]:
x[:,:,1]

tensor([[2, 5, 8]])

In [129]:
# 세미콜론을 사용하여 1개의 차원이 남아있다.
x[:,1,1]

tensor([5])

In [130]:
x[0,0,:]

tensor([1, 2, 3])

In [131]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## PyTorch tensors & NumPy

Numpy is a popular scientific python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data is NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `tensor.Tensor.numpy()`

In [132]:
import torch
import numpy as np

array = np.arange(1., 8)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [133]:
array.dtype

dtype('float64')

In [134]:
tensor.dtype

torch.float64

In [135]:
array = np.arange(1.,8).dtype
tensor = torch.from_numpy(array)
array, tensor

torch.float32

In [136]:
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [137]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [138]:
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networsk and Pytorch comes the concept of a **random seed.**
Essentially what the random seed does is "Flavour" the randomness.


In [140]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7247, 0.1964, 0.6743, 0.6879],
        [0.2696, 0.8814, 0.3813, 0.5524],
        [0.3131, 0.3972, 0.2405, 0.7514]])
tensor([[0.6868, 0.2064, 0.3656, 0.1420],
        [0.7732, 0.4973, 0.0176, 0.0478],
        [0.7591, 0.7927, 0.4812, 0.4610]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [142]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + PyTorch working behind the scenes to make everithing hunkydory (good).

### 1. gettign a GPU

1. Easiest - use google colab for a free gpu
2. use your own gpu - takes a little bit of setup and requires investment of purchase
3. use cloud computing - gcp, aws, azure, these services allow you to rent computers on the cloud and access them

In [147]:
!nvidia-smi

Thu Dec 28 04:10:59 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090         On | 00000000:1D:00.0 Off |                  N/A |
| 30%   36C    P8               34W / 350W|  13097MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with Pytorch

In [148]:
import torch

torch.cuda.is_available()

True

In [150]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [152]:
torch.cuda.device_count()

8

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GOU is because using a GPU results in faaster computation

In [153]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [154]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [157]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [158]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [161]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises & Extra curriculum

In [164]:
rand_tensor = torch.rand(7,7)
rand_tensor.shape

torch.Size([7, 7])

In [166]:
rand_tensor2 = torch.rand(1,7)
rand_tensor2.shape

torch.Size([1, 7])

In [167]:
matmul_tensor = torch.matmul(rand_tensor, rand_tensor2.T)

In [168]:
matmul_tensor

tensor([[1.8826],
        [0.9401],
        [1.6033],
        [0.9660],
        [1.5830],
        [2.1800],
        [1.8788]])

In [169]:
RAND_SEED = 0

In [170]:
torch.manual_seed(RAND_SEED)

rand_tensor = torch.rand(7,7)
rand_tensor.shape
rand_tensor2 = torch.rand(1,7)
rand_tensor2.shape
matmul_tensor = torch.matmul(rand_tensor, rand_tensor2.T)
matmul_tensor

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [183]:
torch.cuda.manual_seed(1234)

In [176]:
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)

tensor_A_gpu = tensor_A.to(device)
tensor_B_gpu = tensor_B.to(device)

In [177]:
tensor_A_gpu

tensor([[0.8102, 0.9801, 0.1147],
        [0.3168, 0.6965, 0.9143]], device='cuda:0')

In [184]:
tensor_A_on_gpu = torch.rand(2,3,device= device)
tensor_B_on_gpu = torch.rand(2,3,device= device)
tensor_A_on_gpu, tensor_B_on_gpu

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

In [185]:
tensor_B_on_gpu

tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')

In [186]:
new = torch.matmul(tensor_A_on_gpu, tensor_B_on_gpu.T)

In [187]:
new

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

In [188]:
new.max()

tensor(0.7668, device='cuda:0')

In [189]:
new.min()

tensor(0.2786, device='cuda:0')

In [190]:
new.argmax()

tensor(1, device='cuda:0')

In [191]:
new.argmin()

tensor(0, device='cuda:0')

In [197]:
rand_one = torch.rand(1,1,1,10)
rand_squeeze = rand_one.squeeze()

In [198]:
rand_squeeze.shape

torch.Size([10])

In [196]:
rand_one.reshape(10).shape

torch.Size([10])